### PR TITLE
IAM

### PR DESCRIPTION
**Pull request by UsadaPeko**

### CODE REVIEW

**Comment by UsadaPeko** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_iam_policy.policy will be created
+ resource "aws_iam_policy" "policy" {
      + arn         = (known after apply)
      + description = "My test policy"
      + id          = (known after apply)
      + name        = "test_policy"
      + path        = "/"
      + policy      = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "ec2:Describe*",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id   = (known after apply)
      + tags_all    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.pekora.dev/lock?id=UsadaPeko%252Finfra-as-a-code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by Miiuuna — APPROVED** [review]

**Comment by UsadaPeko** [comment]
atlantis apply

**Comment by UsadaPeko** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_iam_policy.policy: Creating...
aws_iam_policy.policy: Creation complete after 2s [id=arn:aws:iam::356401180523:policy/test_policy]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
atlantis plan

**Comment by UsadaPeko** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_iam_policy.policy has changed
~ resource "aws_iam_policy" "policy" {
        id          = "arn:aws:iam::356401180523:policy/test_policy"
        name        = "test_policy"
      + tags        = {}
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.pekora.dev/lock?id=UsadaPeko%252Finfra-as-a-code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
atlantis apply

**Comment by UsadaPeko** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
이거 제가 atlantis apply를 할 수 있는데

괜찮은건가요?

@UsadaPeko

**Comment by UsadaPeko** [comment]
atlantis unlock

**Comment by UsadaPeko** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Pull request merged**
