### PR TITLE
test

### PR DESCRIPTION
**Pull request by UsadaPeko**

### CODE REVIEW

**Comment by UsadaPeko** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/home/ubuntu/datas/bin/terraform1.1.5 plan -input=false -refresh -out \"/home/ubuntu/datas/repos/UsadaPeko/infra-as-a-code/15/default/default.tfplan\"" in "/home/ubuntu/datas/repos/UsadaPeko/infra-as-a-code/15/default": exit status 1
╷
│ Error: Saving a generated plan is currently not supported
│ 
│ The "remote" backend does not support saving the generated execution plan
│ locally at this time.
╵

```

**Comment by UsadaPeko** [comment]
atlantis plan

**Comment by UsadaPeko** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_key_pair.pekora-main-keypair has changed
~ resource "aws_key_pair" "pekora-main-keypair" {
        id          = "pekora-main-keypair"
      + tags        = {}
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_instance.backstage_server will be updated in-place
~ resource "aws_instance" "backstage_server" {
        id                                   = "i-0b7a1feb2086fae13"
      ~ tags                                 = {
          ~ "Name" = "UsakenBackstageEC2AAA" -> "UsakenBackstageEC2"
        }
      ~ tags_all                             = {
          ~ "Name" = "UsakenBackstageEC2AAA" -> "UsakenBackstageEC2"
        }
        # (28 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.pekora.dev/lock?id=UsadaPeko%252Finfra-as-a-code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by Miiuuna — APPROVED** [review]

**Comment by UsadaPeko** [comment]
atlantis apply

**Comment by UsadaPeko** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_instance.backstage_server: Modifying... [id=i-0b7a1feb2086fae13]
aws_instance.backstage_server: Modifications complete after 0s [id=i-0b7a1feb2086fae13]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.


```

**Comment by UsadaPeko** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by UsadaPeko** [comment]
atlantis plan

**Comment by UsadaPeko** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
