### PR TITLE
test

### PR DESCRIPTION
**Pull request by UsadaPeko**

### CODE REVIEW

**Comment by UsadaPeko** [comment]
Ran Plan for dir: `tabasco` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.backstage_server will be created
+ resource "aws_instance" "backstage_server" {
      + ami                                  = "ami-0454bb2fefc7de534"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "pekora-main-key"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "UsakenBackstageServer"
        }
      + tags_all                             = {
          + "Name" = "UsakenBackstageServer"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # aws_instance.test will be created
+ resource "aws_instance" "test" {
      + ami                                  = "ami-0454bb2fefc7de534"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "pekora-main-key"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "test"
        }
      + tags_all                             = {
          + "Name" = "test"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # aws_key_pair.pekora-main-keypair will be created
+ resource "aws_key_pair" "pekora-main-keypair" {
      + arn             = (known after apply)
      + fingerprint     = (known after apply)
      + id              = (known after apply)
      + key_name        = "pekora-main-keypair"
      + key_name_prefix = (known after apply)
      + key_pair_id     = (known after apply)
      + public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlsYc+hEFl8tF1jPf4BFWOleo7Z/rGSEcB0pD/TNpcQj2jQvOqyy/kkj17FVLqeZCDVCUHc4xpMmC5d2d4t0SW5vGIdz87k/QUe8w/dyoHlTo/oTqI8yw+17FfbHjb2MmRSe1og1DKn6Wd18pn0hRS0ekZ57fO2aE94cDB52qouKwLBiJnjIEttr8nffHCZeuV+z4PSy63s5gGxsECarjBrb4qKKH9EZYXz91Z7cwRWe31J/3g+P/++KH1wt6ehKsBFd//oM0oKNjxGZc3xacY0rWiZ45pH0QNMvJMlg2hNc0ITOPaM5enxcuAS9FZVNSmYBeEViJNpsctKJi8LVxkS/9ujSZmxOrpbcY6k0nTu5scHnLOPyxOA0ZGCWcYvs2FtwwX7hr7v8xO8ksJHCWnZAj+w18DsxtB842yFq2WIXnB77Rg+lXj1knZs9x3o3k3c1pbBc2DBui859oEyqT2/1AyP/uqUZZU6HORvQsVMLIgE3yxcPp99oaM/6v8C00="
      + tags_all        = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d tabasco`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.pekora.dev/lock?id=UsadaPeko%252Finfra-as-a-code%252Ftabasco%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d tabasco`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by UsadaPeko** [comment]
atlantis apply

**Comment by UsadaPeko** [comment]
Ran Apply for dir: `tabasco` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/UsadaPeko/infra-as-a-code/3/default/tabasco/default.tfplan\"" in "/home/atlantis/.atlantis/repos/UsadaPeko/infra-as-a-code/3/default/tabasco": exit status 1
aws_instance.test: Creating...
aws_instance.backstage_server: Creating...
aws_key_pair.pekora-main-keypair: Creating...
aws_instance.test: Still creating... [10s elapsed]
aws_instance.backstage_server: Still creating... [10s elapsed]
aws_instance.test: Still creating... [20s elapsed]
aws_instance.backstage_server: Still creating... [20s elapsed]
aws_instance.test: Still creating... [30s elapsed]
aws_instance.backstage_server: Still creating... [30s elapsed]
aws_instance.test: Creation complete after 31s [id=i-0b43cf05f26629bf3]
aws_instance.backstage_server: Creation complete after 31s [id=i-081642c42729bdea5]

Error: error importing EC2 Key Pair (pekora-main-keypair): InvalidKeyPair.Duplicate: The keypair 'pekora-main-keypair' already exists.
	status code: 400, request id: 6f07cdba-2fae-4e0d-a19d-1ce3575cc0c5

  with aws_key_pair.pekora-main-keypair,
  on pekora-keypair.tf line 1, in resource "aws_key_pair" "pekora-main-keypair":
   1: resource "aws_key_pair" "pekora-main-keypair" {


```
</details>

**Comment by UsadaPeko** [comment]
atlantis apply

**Comment by UsadaPeko** [comment]
Ran Apply for dir: `tabasco` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/UsadaPeko/infra-as-a-code/3/default/tabasco/default.tfplan\"" in "/home/atlantis/.atlantis/repos/UsadaPeko/infra-as-a-code/3/default/tabasco": exit status 1
aws_instance.test: Creating...
aws_instance.backstage_server: Creating...
aws_key_pair.pekora-main-keypair: Creating...
aws_instance.test: Still creating... [10s elapsed]
aws_instance.backstage_server: Still creating... [10s elapsed]
aws_instance.test: Still creating... [20s elapsed]
aws_instance.backstage_server: Still creating... [20s elapsed]
aws_instance.test: Still creating... [30s elapsed]
aws_instance.backstage_server: Still creating... [30s elapsed]
aws_instance.backstage_server: Creation complete after 31s [id=i-0025ea4a44819f694]
aws_instance.test: Creation complete after 32s [id=i-0ee8264def264052b]

Error: error importing EC2 Key Pair (pekora-main-keypair): InvalidKeyPair.Duplicate: The keypair 'pekora-main-keypair' already exists.
	status code: 400, request id: dfc7c9f5-8882-475f-bbc9-4fd0082758bf

  with aws_key_pair.pekora-main-keypair,
  on pekora-keypair.tf line 1, in resource "aws_key_pair" "pekora-main-keypair":
   1: resource "aws_key_pair" "pekora-main-keypair" {


```
</details>

**Comment by MagicalLas** [comment]
atlantis apply

**Comment by UsadaPeko** [comment]
Ran Apply for dir: `tabasco` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/UsadaPeko/infra-as-a-code/3/default/tabasco/default.tfplan\"" in "/home/atlantis/.atlantis/repos/UsadaPeko/infra-as-a-code/3/default/tabasco": exit status 1
aws_instance.backstage_server: Creating...
aws_key_pair.pekora-main-keypair: Creating...
aws_instance.test: Creating...
aws_instance.backstage_server: Still creating... [10s elapsed]
aws_instance.test: Still creating... [10s elapsed]
aws_instance.backstage_server: Still creating... [20s elapsed]
aws_instance.test: Still creating... [20s elapsed]
aws_instance.backstage_server: Still creating... [30s elapsed]
aws_instance.test: Still creating... [30s elapsed]
aws_instance.test: Creation complete after 31s [id=i-0bb6e2cd4c8565b96]
aws_instance.backstage_server: Still creating... [40s elapsed]
aws_instance.backstage_server: Creation complete after 42s [id=i-071699e407ecd85ae]

Error: error importing EC2 Key Pair (pekora-main-keypair): InvalidKeyPair.Duplicate: The keypair 'pekora-main-keypair' already exists.
	status code: 400, request id: b876a2f5-66d7-43e1-b43e-dd2b52c0ad18

  with aws_key_pair.pekora-main-keypair,
  on pekora-keypair.tf line 1, in resource "aws_key_pair" "pekora-main-keypair":
   1: resource "aws_key_pair" "pekora-main-keypair" {


```
</details>

**Comment by UsadaPeko** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `tabasco` workspace: `default`

**Pull request closed without merging**
